# Myrcast Configuration File
# Weather Report Generator with AI and Speech

[apis]
# Get your OpenWeather API key at: https://openweathermap.org/api
openweather = "your-openweather-api-key-here"

# Get your Anthropic API key at: https://console.anthropic.com/
anthropic = "your-anthropic-api-key-here"

# Get your ElevenLabs API key at: https://elevenlabs.io/
elevenlabs = "your-elevenlabs-api-key-here"

[weather]
# Coordinates for your location (example: San Francisco)
latitude = 37.7749
longitude = -122.4194

# Units: "metric", "imperial", or "kelvin"
units = "imperial"

[output]
# Directory for temporary files
temp_directory = "/tmp/myrcast"

# Directory where Myriad should import generated content
import_path = "/Users/username/Documents/Myrcast"

# Base filename for generated audio files (without extension)
# The .wav extension will be added automatically
media_id = "weather_report"

[prompt]
# Template for AI weather report generation
# Describe the style, tone, and format you want for your weather reports
# Claude will automatically extract relevant details from the weather data provided
template = "You are a professional radio weather announcer for morning drive time. Generate a 20-second weather report that's upbeat and informative. Include current conditions, today's high and low temperatures, and any weather to watch for. Use conversational language that sounds natural when spoken aloud. Keep it concise and engaging for busy commuters."

[claude]
# Claude model to use (defaults to claude-3-5-sonnet-20241022)
# Available models: claude-3-5-sonnet-20241022, claude-3-opus-20240229, claude-3-haiku-20240307
model = "claude-3-5-sonnet-20241022"

# Maximum tokens to generate (100-4096)
max_tokens = 1000

# Temperature for response generation (0-1, higher = more creative)
temperature = 0.7

# Retry and rate limiting configuration
# Maximum number of retry attempts for failed requests (default: 3)
max_retries = 3

# Base delay between retries in milliseconds (default: 1000)
base_delay_ms = 1000

# Maximum delay between retries in milliseconds (default: 30000)
max_delay_ms = 30000

# Rate limit - maximum requests per minute (default: 50)
rate_limit = 50

[elevenlabs]
# Voice ID from ElevenLabs (find at https://elevenlabs.io/voice-library)
# Default is "pNInz6obpgDQGcFmaJgB" (Adam voice)
voice_id = "pNInz6obpgDQGcFmaJgB"

# Voice model to use for text-to-speech generation
# Options: eleven_multilingual_v1, eleven_monolingual_v1, eleven_turbo_v2
model = "eleven_multilingual_v1"

# Voice stability (0.0-1.0, higher = more stable/consistent)
# Lower values allow more variation, higher values are more consistent
stability = 0.5

# Similarity boost (0.0-1.0, higher = more similar to original voice)
# Controls how closely the AI attempts to replicate the voice
similarity = 0.8

# Style exaggeration (0.0-1.0, higher = more expressive)
# Controls the exaggeration of the speaking style
style = 0.0

# Speaking speed (0.7-1.2, higher = faster speech)
# 1.0 is normal speed, ElevenLabs enforces 0.7-1.2 range
speed = 1.0

# Audio format: ElevenLabs format (codec_samplerate_bitrate)
# Examples: mp3_44100_128, pcm_16000, ulaw_8000
format = "mp3_44100_128"

# Retry and rate limiting configuration
# Maximum number of retry attempts for failed requests (default: 3)
max_retries = 3

# Base delay between retries in milliseconds (default: 1000)
base_delay_ms = 1000

# Maximum delay between retries in milliseconds (default: 30000)
max_delay_ms = 30000

# Rate limit - maximum requests per minute (default: 20, conservative for ElevenLabs)
rate_limit = 20