# Myrcast Configuration File
# Weather Report Generator with AI and Speech

[apis]
# Get your OpenWeather API key at: https://openweathermap.org/api
openweather = "your-openweather-api-key-here"

# Get your Anthropic API key at: https://console.anthropic.com/
anthropic = "your-anthropic-api-key-here"

# Get your ElevenLabs API key at: https://elevenlabs.io/
elevenlabs = "your-elevenlabs-api-key-here"

[weather]
# Coordinates for your location (example: San Francisco)
latitude = 37.7749
longitude = -122.4194

# Units: "metric", "imperial", or "kelvin"
units = "imperial"

[output]
# Directory for temporary files
temp_directory = "/tmp/myrcast"

# Directory where Myriad should import generated content
import_path = "/Users/username/Documents/Myrcast"

# Base filename for generated audio files (without extension)
media_id = "weather_report"

[prompt]
# Template for AI weather report generation
template = "You are a friendly weather reporter. Generate an engaging weather report for the location based on the provided weather data. Include current conditions, temperature, and any notable weather patterns. Keep it conversational and informative."

[claude]
# Claude model to use
model = "claude-3-5-sonnet-20241022"

# Maximum tokens to generate (100-4096)
max_tokens = 1000

# Temperature for response generation (0-1, higher = more creative)
temperature = 0.7

[elevenlabs]
# Voice ID from ElevenLabs
voice_id = "pNInz6obpgDQGcFmaJgB"

# Voice model to use
model = "eleven_multilingual_v1"

# Voice stability (0.0-1.0)
stability = 0.5

# Similarity boost (0.0-1.0)
similarity = 0.8

# Style exaggeration (0.0-1.0)
style = 0.0

# Speaking speed (0.7-1.2)
speed = 1.0

# Audio format (ElevenLabs format)
format = "mp3_44100_128"

[logging]
# Enable file logging
enabled = true

# Log directory
directory = "logs"

# Log filename pattern
filename_pattern = "myrcast-YYYYMMDD.log"

# Log level: debug, info, warn, error
level = "info"

# Keep 7 days of logs
max_files = 7

# Rotate when file exceeds 10MB
max_size_mb = 10

# Also output to console
console_output = true