# Myrcast Configuration File
# Weather Report Generator with AI and Speech

[apis]
# Get your OpenWeather API key at: https://openweathermap.org/api
openweather = "your-openweather-api-key-here"

# Get your Anthropic API key at: https://console.anthropic.com/
anthropic = "your-anthropic-api-key-here"

[weather]
# Coordinates for your location (example: San Francisco)
latitude = 37.7749
longitude = -122.4194

# Units: "metric", "imperial", or "kelvin"
units = "imperial"

[output]
# Directory for temporary files
temp_directory = "/tmp/myrcast"

# Directory where Myriad should import generated content
import_path = "/Users/username/Documents/Myrcast"

[speech]
# Voice ID for ElevenLabs (any voice name or ID)
voice = "alloy"

# Speech speed (0.1 to 4.0)
speed = 1.0

# Audio format: ElevenLabs format (codec_samplerate_bitrate)
# Examples: mp3_44100_128, pcm_16000, ulaw_8000
format = "mp3_44100_128"

[prompt]
# Template for AI weather report generation
# You can use variables like {{location}}, {{current_temp}}, {{conditions}}, etc.
template = "You are a friendly weather reporter. Generate an engaging weather report for {{location}} based on the provided weather data. Include current conditions, temperature, and any notable weather patterns. Keep it conversational and informative."

[claude]
# Claude model to use (defaults to claude-3-5-sonnet-20241022)
# Available models: claude-3-5-sonnet-20241022, claude-3-opus-20240229, claude-3-haiku-20240307
model = "claude-3-5-sonnet-20241022"

# Maximum tokens to generate (100-4096)
max_tokens = 1000

# Temperature for response generation (0-1, higher = more creative)
temperature = 0.7