# Myrcast Configuration File
# Weather Report Generator with AI and Speech
#
# Copy this file to config.toml or dev.toml and edit with your API keys

[apis]
# Get your OpenWeather API key at: https://openweathermap.org/api
openweather = "your-openweather-api-key-here"

# Get your Anthropic API key at: https://console.anthropic.com/
anthropic = "your-anthropic-api-key-here"

# Get your ElevenLabs API key at: https://elevenlabs.io/
elevenlabs = "your-elevenlabs-api-key-here"

[weather]
# Coordinates for your location (example: San Francisco)
latitude = 37.7749
longitude = -122.4194

# Units: "metric", "imperial", or "kelvin"
units = "imperial"

[output]
# Directory where Myriad should import generated content
# Windows example: "C:\\Myriad\\Import"
# macOS/Linux example: "/Users/username/Documents/Myrcast"
import_path = "/Users/username/Documents/Myrcast"

# Base filename for generated audio files (without extension)
media_id = "weather_report"

[prompt]
# Template for AI weather report generation
# This is an instruction to the AI, not a template with variables
template = "You are a professional radio weather announcer for morning drive time. Generate a 20-second weather report that's upbeat and informative. Include current conditions, today's high and low temperatures, and any weather to watch for. Use conversational language that sounds natural when spoken aloud."

[claude]
# Claude model to use
model = "claude-3-5-sonnet-20241022"

# Maximum tokens to generate (100-4096)
max_tokens = 1000

# Temperature for response generation (0-1, higher = more creative)
temperature = 0.7

# Retry settings
max_retries = 3
base_delay_ms = 1000
max_delay_ms = 30000

# Rate limiting (requests per minute)
rate_limit = 50

[elevenlabs]
# Voice ID from ElevenLabs (find at https://elevenlabs.io/voice-library)
# Professional male voice (default): "pNInz6obpgDQGcFmaJgB"
# Professional female voice: "EXAVITQu4vr4xnSDxMaL"
voice_id = "pNInz6obpgDQGcFmaJgB"

# Voice model to use
model = "eleven_multilingual_v1"

# Voice stability (0.0-1.0, higher = more stable/consistent)
stability = 0.5

# Similarity boost (0.0-1.0, higher = more similar to original voice)
similarity = 0.8

# Style exaggeration (0.0-1.0, higher = more expressive)
style = 0.0

# Speaking speed (0.7-1.2, 1.0 = normal speed)
# ElevenLabs enforces 0.7-1.2 range
speed = 1.0

# Audio format: ElevenLabs format (codec_samplerate_bitrate)
# Examples: mp3_44100_128, pcm_16000, ulaw_8000
format = "mp3_44100_128"

# Retry settings
max_retries = 3
base_delay_ms = 1000
max_delay_ms = 30000

# Rate limiting (requests per minute)
rate_limit = 20

[logging]
# Enable file logging with rotation
enabled = true

# Log directory (relative or absolute path)
directory = "logs"

# Log filename pattern (supports YYYY, MM, DD patterns)
filename_pattern = "myrcast-YYYYMMDD.log"

# Log level: debug, info, warn, error
level = "info"

# Keep this many log files (7 = one week)
max_files = 7

# Rotate when file exceeds this size in MB
max_size_mb = 10

# Also output logs to console
console_output = true

[cache]
# Weather data caching configuration
# Leave empty to use system temp directory (recommended)
# Cache automatically expires at midnight local time
file_path = ""